### PR TITLE
Rename main nav item »Medias« to »media«

### PR DESCRIPTION
**Pull request by mischah**
… and update the title :kissing_heart:

because of consistency.

@LukyVj @Haroenv 
Do you agree with that?

### CODE REVIEW

**Comment by LukyVj** [comment]
Sure! :)

**Comment by Haroenv** [comment]
yeah sure

**Comment by mischah** [comment]
:ok_hand:

**Comment by Haroenv** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by mischah** [comment]
̿̿̿̿̿̿̿̿̿·̿̿̿̿̿̿̿̿·̿̿̿̿̿̿̿·̿̿̿̿̿̿·̿̿̿̿̿·̿̿̿̿· ̿̿̿·̿̿·̿·͇·͇͇·͇͇͇·͇͇͇͇ ...

**Pull request merged**
