### PR TITLE
Added search

### LINKED ISSUE #58: Search bar
A search bar to search for repositories directly on [bullg.it](https://bullg.it) would be great.

### PR DESCRIPTION
**Pull request by Haroenv**
I know @LukyVj, it's not algolia, but boring my version is still better than no search at all.

cc @JohJakob 

Fixes #58 

Review wanted!

### CODE REVIEW

**Comment by LukyVj** [comment]
Just the var name as mentionned in the comment and 🚀

**Comment by dervondenbergen** [comment]
I think it is a bit too big, looks weird. Why not a smaller font size and having the same width as 2 repos, not just a little bit smaller?

**Comment by Haroenv** [comment]
You're right @dervondenbergen, I didn't edit any of the style when I copied it over, I don't seem to find how to get it to be the same size as two projects though

**Comment by dervondenbergen** [comment]
`padding: 1em 0` instead of `padding: 1em` on `.search`

**Comment by Haroenv** [comment]
What about this:



just found that too

**Comment by LukyVj** [comment]
Hm that's a big thick, sorry I couldn't see it I'm on mobile.
Just make it less thick somehow, a smaller font-size and lighter border.

We could still change the design later.

**Comment by Haroenv** [comment]
like this?

**Comment by LukyVj** [comment]
Much much better👌✌️
Well done!

🚀

**Comment by Haroenv** [comment]
so, :shipit: ?

**Comment by LukyVj** [comment]
Yep!
At least from my side!! 

🐮💩

**Comment by LukyVj** [comment]
Poke @dervondenbergen

**Comment by Haroenv** [comment]
it's live, check it out on https://bullg.it

**Comment by LukyVj** [comment]
Yey, but to fix on mobile

**Comment by dervondenbergen** [comment]
ah, yeah, also from me :shipit: :joy:

**Comment by Haroenv** [comment]
What needs to be fixed @LukyVj ? I see no errors

**Comment by LukyVj** [comment]
But well done! It's really cool 😎
Could be cool to make it full width on mobile, maybe

     width: calc(90% - 16px);
     margin: 0 8px;

And it will be perfect!

**Comment by Haroenv** [comment]
what do you mean, it's spanning all the width, so it's full width already `width: 100%`

**Comment by LukyVj** [comment]
My bad, it used to look like this : 


But now it's fixed :)

**Comment by Haroenv** [comment]
probably `style.css` being cached or something

**Comment by dervondenbergen** [comment]
looks good for me:
img_1271

**Comment by JohJakob** [comment]
@Haroenv Perfect! Nice work!

**Comment by TimPietrusky** [comment]
Super awesome +1

**Pull request merged**
