### PR TITLE
add links

### LINKED ISSUE #48: put link to github pages version if available.
code snippet for reference:

```liquid
{% assign repos = site.github.public_repositories | sort: 'created_at' | reverse%}
{% for repo in repos %}
{% unless repo.fork %}
<article>
  {{repo.created_at}}
  <h2><a href="{{ repo.html_url }}">{{ repo.name }}</a></h2>
  {% if repo.has_pages %}
    <a href="https://bullg.it/{{ repo.name }}" class="ext">🌐 {{ repo.name }}</a>
  {% else %}
    {% if repo.homepage.size > 0 %}
    <a href="{{repo.homepage}}" class="ext">🌐 {{ repo.name }}</a>
    {% endif %}
  {% endif %}
  <p>{{ repo.description}}</p>
</article>
{% endunless %}
{% endfor %}
```

With `repo.homepage` the link you put in the description on top, and `repo.has_pages` to check if it has a `gh-pages` branch.

IMO a link in the top right of each card with `🌐` as text would be good.

### PR DESCRIPTION
**Pull request by Haroenv**
Would fix #48 

Needs review considering the placement & content of the links ( @0x04, is that emoji okay on Widnows)

### CODE REVIEW

**Comment by Haroenv** [comment]
In case the emoji isn't okay, we can include the gem 

`jekyll-jemoji` I think, and then use `:globe_with_meridians:` or one of entypo, since that's included already.

**Comment by dervondenbergen** [comment]
jemoji is a good idea, they are supported on github pages: https://help.github.com/articles/emoji-on-github-pages/

**Comment by Haroenv** [comment]
jemoji is no option, it doesn't work in html https://github.com/jekyll/jemoji/pull/29

**Comment by dervondenbergen** [comment]
I'm ok with it :+1:

**Pull request merged**
