### PR TITLE
making a bit more of the blog a reality [WIP] [dontmerge]

### PR DESCRIPTION
**Pull request by Haroenv**
This is just because there is already a post made, so why not make more of them and actually make them visible
- [ ] a real first post
- [ ] copy/link anniversary posts by @reimersjan @LukyVj @kevingimbel @TimPietrusky @dervondenbergen 
- [x] archive
- [ ] header item
- [x] absolute linking of assets in `header` and `footer`
- [x] some fixes in style
- [x] `<a href='/'></a>` on header to get easily to home

### CODE REVIEW

**Comment by LukyVj** [comment]
:+1:*2

**Comment by dervondenbergen** [comment]
Will we drop blog.bullg.it then? I'm ok with it

**Comment by dervondenbergen** [comment]
regarding showing the posts.

one idea i had once, was to display the latest blog post beside the latest/featured repo

**Comment by Haroenv** [comment]
Yeah, I don't think it's necessary to have ghost if you have Jekyll already

**Comment by dervondenbergen** [comment]
I have an idea regarding the anniversary posts (or any other post about bullgit on someones blog): There could be the real text post and a link post, which appears as the same, but actually just links to the other blog. Like on css tricks

**Comment by Haroenv** [comment]
good idea!

**Comment by LukyVj** [comment]
Where we at ?

**Comment by Haroenv** [comment]
I think it's waiting for a real first post mostly (and a rebase)

**Comment by kevingimbel** [comment]
@Haroenv merge this into master if you want to. :+1:

**Comment by Haroenv** [comment]
First need to copy a blogpost right?

**Comment by kevingimbel** [comment]
@Haroenv just a generic "ok" from my site because you habe `[dontmerge]` in your title and I'm prompted to compare & merge by GitHub. :)

**Comment by Haroenv** [comment]
Someone else can reopen this when they have an idea for some blogs 👍

**Pull request closed without merging**
