### PR TITLE
bye bye

### PR DESCRIPTION
**Pull request by pixelass**

### CODE REVIEW

**Comment by Haroenv** [comment]
Are you sure?

**Comment by pixelass** [comment]
can someone please merge this?

**Comment by LukyVj** [comment]
Yes, we could... But a bit of explainations would be really cool Greg.
I wonder how & why you just turned up like this.

But sure, if you wanna go, you can. 
It's just not cool to spit on the soup you use to drink.

**Comment by LukyVj** [comment]
Asta la vista.

**Comment by kevingimbel** [comment]
I'm cut out of that pic :( #notcool

**Comment by LukyVj** [comment]
But we're all here ! On the second one I have, you're kinda invisible :x

**Comment by TimPietrusky** [comment]
Bullsterdam was awesome! It's so sad that we don't have time machines already :'(

**Comment by kevingimbel** [comment]
We need to do this again! <3

**Pull request merged**
