### PR TITLE
Add yadomi to members list

### PR DESCRIPTION
**Pull request by yadomi**

### CODE REVIEW

**Comment by dervondenbergen** [comment]
The css didn't change, but the `_site` directory got changed.
It is actually not needed, so I would remove it actually.

**Comment by yadomi** [comment]
@dervondenbergen you're right, but I think `_site` should be in the `.gitignore` no ?

**Comment by dervondenbergen** [comment]
yes, it should be

**Comment by yadomi** [comment]
@dervondenbergen lol, in fact, `_site` is in the `.gitignore` but files in this directory are still tracked '-'

**Comment by dervondenbergen** [comment]
maybe we have to remove the `_site` folder from the `.gitignore` and also the folder itself and commit those removals
adding `_sites` back to the ignore could maybe solve the problem, but i have no idea

**Comment by yadomi** [comment]
`git rm -r --cached _site` then `git add .` and then commit should do the trick @dervondenbergen

**Comment by dervondenbergen** [comment]
Can you look if this works as expected and simply put it to your pr or make a new one, how you like it better (what's easier for you)

**Comment by yadomi** [comment]
@dervondenbergen here your https://github.com/bullgit/bullgit.github.io/pull/28 :)

**Pull request merged**
