### PR TITLE
Add stars

### LINKED ISSUE #54: Show amount of stars on each repository
Also pretty easy to get out of the github metadata

### PR DESCRIPTION
**Pull request by Haroenv**
Not really sure of the implementation right now.

fixes #54

### CODE REVIEW

**Comment by LukyVj** [comment]
Where we at ?

**Comment by Haroenv** [comment]
It works but I thought the concensus was it isn't pretty

**Comment by dervondenbergen** [comment]
should we actually GTM? @Haroenv

**Comment by Haroenv** [comment]
Yesh, just get this merged 🗡

**Pull request merged**
