### PR TITLE
Nav fix

### PR DESCRIPTION
**Pull request by dervondenbergen**

### CODE REVIEW

**Comment by dervondenbergen** [comment]
@Haroenv I think the style should be correct now. Do you mind testing the changes on your machine before merging?

**Comment by Haroenv** [comment]
Because I don't have compass (and can't install it, #justElCapProblems) i still can't compile, but it's seems like it's fine now

**Comment by dervondenbergen** [comment]
perfect, let's someone else test it, before merging

**Comment by Haroenv** [comment]
@bullgit/gitches @bullgit/owners pls

**Comment by Haroenv** [comment]
I just noticed why I still had that compass error, it was because I wasn't in the right branch trying it out (stupid of me), but your fix doesn't actually do what https://github.com/bullgit/bullgit.github.io/issues/25 was supposed to do

**Comment by Haroenv** [comment]
So my guess is that it should be recompiled now

**Comment by Haroenv** [comment]
yep, now it's all on one line LGTM

**Pull request closed without merging**
