### PR TITLE
using our own piwik installation

### PR DESCRIPTION
**Pull request by dervondenbergen**
replacing Google Analytics code with Piwik Code,

like discussed here: https://github.com/bullgit/bullgit.github.io/issues/21

### CODE REVIEW

**Comment by dervondenbergen** [comment]
before merging, we have to copy all the google analytics data to piwik

**Comment by dervondenbergen** [comment]
which is not possible right now, which is dumb

i don't know if we should merge or not

**Comment by kevingimbel** [comment]
Since we wouldn't lose data I'd say merge and go fot it. We can then still export the Google Analytics Data to CSV and see if we can do anything with it.

**Comment by dervondenbergen** [comment]
True, nothing gets lost.

**Comment by kevingimbel** [comment]
I merged it. Guess this issue can be closed then.

**Pull request merged**
