### PR TITLE
uncompassify

### PR DESCRIPTION
**Pull request by Haroenv**
No more compass https://github.com/bullgit/bullgit.github.io/issues/25#issuecomment-131503514

### CODE REVIEW

**Comment by dervondenbergen** [comment]
I'll take a look at the pr in the evening if also for me everything works.

**Comment by dervondenbergen** [comment]
@Haroenv 
the new compassfree code doesn't include the changes from #33 
please reuncompassify again with the fixed nav

**Comment by Haroenv** [comment]
Technically they don’t touch the same subjects so it should work, but for good measure:

**Comment by dervondenbergen** [comment]
I just preview the uncompassify branch on my local machine, and there was the broken nav

**Comment by Haroenv** [comment]
Also now after updating to lower that left margin?

**Comment by dervondenbergen** [comment]
oh, wait, didn't see the pr update, sorry

**Comment by dervondenbergen** [comment]
perfect, looks correctly now :+1:

**Comment by Haroenv** [comment]
LGTM too

**Pull request merged**
