### PR TITLE
Revert "fix for the nav breaking"

### PR DESCRIPTION
**Pull request by dervondenbergen**
this *fix* only breaks things right now

don't merge unless you are @Haroenv

### CODE REVIEW

**Comment by Haroenv** [comment]
Does anyone have compass installed? Compiling it and using the code of #30 would work I think.

**Comment by dervondenbergen** [comment]
I could look in the evening, if I'm able to run compass.

**Comment by Haroenv** [comment]
Then we finally have a proper nav ;)

**Comment by dervondenbergen** [comment]
I'm not able to install compass, or any gem. It could be because I'm on OS X 10.11.
I will try now on my server, running ubuntu.

**Pull request merged**
